### ISSUE TITLE
Use jnaerator-runtime?

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/llvm-j#5]
Currently the repo includes two classes from [jnaerator-runtime](https://github.com/nativelibs4java/JNAerator/tree/master/jnaerator-runtime/src/main/java/com/ochafik/lang/jnaerator/runtime). We could include jnaerator-runtime as a dependency (it is available as a JAR), but it includes a lot more classes.

If we don't do this, than we need to declare the license properly.

**Comment by leostrakosch** [comment]
I decided against including jnaerator-runtime since it's only two small classes that we need.
It also seems that development on jnaerator has stopped (last commit ~3 years ago), so we are not missing any updates if we don't use the full project.

I've added the license declarations to the specific files (also for all other code files),
could you have a quick look whether it is ok how the license is declared, please?
I wouldn't claim that I'm an expert at this.

[LICENSE file](https://github.com/sosy-lab/llvm-j/blob/316ed798b041fb0695375a8f24a79a4771446b7c/LICENSE)
[Example own code](https://github.com/sosy-lab/llvm-j/blob/316ed798b041fb0695375a8f24a79a4771446b7c/src/main/java/org/sosy_lab/llvm_j/Function.java)
[Example jnaerator code](https://github.com/sosy-lab/llvm-j/blob/316ed798b041fb0695375a8f24a79a4771446b7c/src/main/java/org/sosy_lab/llvm_j/binding/ext/NativeSize.java)

**Comment by PhilippWendler** [comment]
Oh, there is a huge problem: JNAerator is GPL, and we cannot use GPL libraries at all. 
Are you sure this is the license of the code? Often such libraries have different licences for themselves and the part of the code that is necessary at runtime (at least for code they have generated), in order to not enforce GPL on all users.

If it is indeed GPL, we need to rewrite all code that is executed at runtime and comes from JNAerator.

**Comment by leostrakosch** [comment]
There is no other license declaration in that project.

What do you mean with 'rewrite'? The classes are not 1:1 the same as the ones you can find in jnaerator-runtime, if that is enough.

[NativeSize.java of Jnaerator](https://github.com/nativelibs4java/JNAerator/blob/ac73c9e491b7211f2e1278fb4a7c6cedd46f0cf5/jnaerator-runtime/src/main/java/com/ochafik/lang/jnaerator/runtime/NativeSize.java)
[NativeSize.java of us](https://github.com/sosy-lab/llvm-j/blob/c47505e0d67344a7a52182390f3643a2b3de17d2/src/main/java/org/sosy_lab/llvm_j/binding/ext/NativeSize.java)

[NativeSizeByReference.java of jnaerator](https://github.com/nativelibs4java/JNAerator/blob/ac73c9e491b7211f2e1278fb4a7c6cedd46f0cf5/jnaerator-runtime/src/main/java/com/ochafik/lang/jnaerator/runtime/NativeSizeByReference.java)
[NativeSizeByReference.java of us](https://github.com/sosy-lab/llvm-j/blob/c47505e0d67344a7a52182390f3643a2b3de17d2/src/main/java/org/sosy_lab/llvm_j/binding/ext/NativeSizeByReference.java)

**Comment by PhilippWendler** [comment]
Rewrite means: through the file away and write code that does what we need it to do from scratch.

But Jnaerator uses LGPL instead of GPL:
https://github.com/nativelibs4java/JNAerator/blob/ac73c9e491b7211f2e1278fb4a7c6cedd46f0cf5/LICENSE.LGPL-3.0.txt
https://code.google.com/archive/p/jnaerator/wikis/CreditsAndLicense.wiki

LGPL is no problem, it just needs to be declared correctly in the header.

The content of [LICENSE.LGPL.header](https://github.com/nativelibs4java/JNAerator/blob/ac73c9e491b7211f2e1278fb4a7c6cedd46f0cf5/LICENSE.LGPL.header) is probably wrong.

It just remains the [question which version of the LGPL it is](https://github.com/nativelibs4java/JNAerator/issues/90).

**Comment by leostrakosch** [comment]
Ah, I didn't even notice that it's different in the header!
I'll change it.

**Comment by leostrakosch** [comment]
For now I put 3.0 there, because it's the license as specified by the common project root.
But since the pom.xml specifies LGPL 2.1 as a license for (among others) jnaerator-runtime,
can't we choose which one we prefer?

**Comment by PhilippWendler** [comment]
We can choose only if it is clear that several licenses apply to the same file. Otherwise we need to use the correct one. I would say, if a file has a license in its header, that license needs to be used, otherwise the one from the documentation. Licenses declared in additional files like `pom.xml` would be used only if there is no other place where a license is declared.

**Comment by leostrakosch** [comment]
Ok, so the problem of the wrong content in the `LICENSE.LGPL.header` stays.

Since we have no clear information on the license, should I note in our files' headers that licensing is not clear?
Everything strongly hints to LGPL 3.0 (source tree license, no header in file itself, but header of LGPL 3.0 in newer files of the same directory), but we can't be sure.

**Comment by PhilippWendler** [comment]
No, we should not redistribute files with an unclear license. This is potentially troublesome and worthless for users.

We need to decide which license we think applies to the files according to our best interpretation of the given facts. If we cannot come to a conclusion and we cannot get an answer from the developers, we simply cannot use these files.

**Comment by leostrakosch** [comment]
If a clear interpretation of the facts is enough, I'd stay with LGPL 3.0 .
But I've written Olivier Chafik and asked him to please clarify the license of jnaerator-runtime and the two files in question - maybe he'll answer.

**Comment by leostrakosch** [comment]
Despite multiple attempts to reach Olivier, he did not answer, I thus don't expect any clarification in this issue, and suggest that we stay with LGPL 3.0 as discussed above.
